services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./agrimlops.db
      - MODEL_PATH=models/model_v1.pt
      - LABEL_MAP_PATH=models/label_map.json
      - MODEL_METADATA_PATH=models/model_v1_metadata.json
      - UPLOAD_DIR=data/feedback/uploads
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./reports:/app/reports
      - ./agrimlops.db:/app/agrimlops.db

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
      - MODEL_METADATA_PATH=models/model_v1_metadata.json
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./reports:/app/reports
    depends_on:
      - api
